
export enum MovieGenre {
  ABSURDIST = 'ABSURDIST', // absurdist/surreal/whimsical
  ACTION = 'ACTION',
  ADVENTURE = 'ADVENTURE',
  COMEDY = 'COMEDY',
  CRIME = 'CRIME',
  DRAMA = 'DRAMA',
  FANTASY = 'FANTASY',
  HISTORICAL = 'HISTORICAL',
  HISTORICAL_FICTION = 'HISTORICAL_FICTION',
  HORROR = 'HORROR',
  MAGICAL = 'MAGICAL realism',
  MYSTERY = 'MYSTERY',
  PARANOID_FICTION = 'PARANOID_FICTION',
  PHILOSOPHICAL = 'PHILOSOPHICAL',
  POLITICAL = 'POLITICAL',
  ROMANCE = 'ROMANCE',
  SAGA = 'SAGA',
  SATIRE = 'SATIRE',
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  SOCIAL = 'SOCIAL',
  SPECULATIVE = 'SPECULATIVE',
  THRILLER = 'THRILLER',
  URBAN = 'URBAN',
  WESTERN = 'WESTERN',
  OTHER = 'OTHER'
}

export enum TVGenre {
  // MovieGenre
  ABSURDIST = 'ABSURDIST', // absurdist/surreal/whimsical
  ACTION = 'ACTION',
  ADVENTURE = 'ADVENTURE',
  COMEDY = 'COMEDY',
  CRIME = 'CRIME',
  DRAMA = 'DRAMA',
  FANTASY = 'FANTASY',
  HISTORICAL = 'HISTORICAL',
  HISTORICAL_FICTION = 'HISTORICAL_FICTION',
  HORROR = 'HORROR',
  MAGICAL = 'MAGICAL realism',
  MYSTERY = 'MYSTERY',
  PARANOID_FICTION = 'PARANOID_FICTION',
  PHILOSOPHICAL = 'PHILOSOPHICAL',
  POLITICAL = 'POLITICAL',
  ROMANCE = 'ROMANCE',
  SAGA = 'SAGA',
  SATIRE = 'SATIRE',
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  SOCIAL = 'SOCIAL',
  SPECULATIVE = 'SPECULATIVE',
  THRILLER = 'THRILLER',
  URBAN = 'URBAN',
  WESTERN = 'WESTERN',

  // TV genre
  LIVE_ACTION_SCRIPTED = 'LIVE_ACTION_SCRIPTED',
  LIVE_ACTION_UNSCRIPTED = 'LIVE_ACTION_UNSCRIPTED',
  OTHER = 'OTHER'
}

export enum AnimeGenre {
  // Movie genre
  ABSURDIST = 'ABSURDIST', // absurdist/surreal/whimsical
  ACTION = 'ACTION',
  CRIME = 'CRIME',
  HISTORICAL = 'HISTORICAL',
  HISTORICAL_FICTION = 'HISTORICAL_FICTION',
  MAGICAL = 'MAGICAL realism',
  MYSTERY = 'MYSTERY',
  PARANOID_FICTION = 'PARANOID_FICTION',
  PHILOSOPHICAL = 'PHILOSOPHICAL',
  POLITICAL = 'POLITICAL',
  SAGA = 'SAGA',
  SATIRE = 'SATIRE',
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  SOCIAL = 'SOCIAL',
  SPECULATIVE = 'SPECULATIVE',
  URBAN = 'URBAN',
  WESTERN = 'WESTERN',

  // anime genre
  KODOMO = 'KODOMO',
  SHONEN = 'SHONEN', // SHŌNEN = 'SHŌNEN',
  SHOJO = 'SHOJO', // SHŌJO = 'SHŌJO',
  SEINEN = 'SEINEN',
  JOSEI = 'JOSEI',
  HAREM = 'HAREM',
  REVERSE = 'REVERSE',
  HENTAI = 'HENTAI',
  ROMANCE = 'ROMANCE',
  HORROR = 'HORROR',
  COMEDY = 'COMEDY',
  FANTASY = 'FANTASY',
  ECCHI = 'ECCHI',
  MECHA = 'MECHA',
  LOLICON = 'LOLICON',
  SHOTACON = 'SHOTACON',
  ISEKAI = 'ISEKAI',
  YAOI = 'YAOI', // Yaoi/shounen-ai
  YURI = 'YURI', // Yuri/shojo-ai
  DRAMA = 'DRAMA',
  SUPERNATURAL = 'SUPERNATURAL',
  THRILLER = 'THRILLER',
  SLICE_OF_LIFE = 'SLICE_OF_LIFE',
  ADVENTURE = 'ADVENTURE',
  OTHER = 'OTHER'
}

export enum DocumentaryGenre {
  ANIMATED = 'ANIMATED',
  DIGITAL_STORYTELLING = 'DIGITAL_STORYTELLING',
  DOCUDRAMA = 'DOCUDRAMA',
  DOCUFICTION = 'DOCUFICTION',
  ETHNOFICTION = 'ETHNOFICTION',
  ETHNOGRAPHIC_FILM = 'ETHNOGRAPHIC_FILM',
  FOUND_FOOTAGE = 'FOUND_FOOTAGE', // (film technic)
  MONDO_FILM = 'MONDO_FILM',
  NATURE = 'NATURE',
  PSEUDO_DOCUMENTARY = 'PSEUDO_DOCUMENTARY',
  REALITY_FILM = 'REALITY_FILM',
  SEMIDOCUMENTARY = 'SEMIDOCUMENTARY',
  TRAVEL = 'TRAVEL',
  VISUAL_SOCIOLOGY = 'VISUAL_SOCIOLOGY',
  OTHER = 'OTHER'
}

export enum PornographyGenre {
  AMATEUR_PORNOGRAPHY = 'AMATEUR',
  BONDAGE_PORNOGRAPHY = 'BONDAGE',
  ETHNIC_PORNOGRAPHY = 'ETHNIC',
  FETISH_PORNOGRAPHY = 'FETISH',
  GROUP_SEX = 'GROUP_SEX',
  REALITY_PORNOGRAPHY = 'REALITY',
  PORN_PARODY = 'PARODY',
  SEXUAL_ORIENTATION_BASED_PORNOGRAPHY = 'SEXUAL_ORIENTATION',
  STRAIGHT_PORN = 'STRAIGHT',
  GAY_PORNOGRAPHY = 'GAY',
  LESBIAN_PORNOGRAPHY = 'LESBIAN',
  BISEXUAL_PORNOGRAPHY = 'BISEXUAL',
  TRANSGENDER_PORNOGRAPHY = 'TRANSGENDER',
  OTHER = 'OTHER'
}

export type Genre =
  MovieGenre
  | TVGenre
  | AnimeGenre
  | DocumentaryGenre
  | PornographyGenre

export const Genre = {
  ...MovieGenre,
  ...TVGenre,
  ...AnimeGenre,
  ...DocumentaryGenre,
  ...PornographyGenre
}

export default Genre
