input MediaInput {
  uri: ID
  origin: ID
  language: String
  id: ID
  url: String
}

input MediaPageInput {
"""Filter by media IDs"""
  nodes: [MediaInput!]
  """Filter by search terms"""
  search: String
  """Filter by the media's current release status"""
  status: MediaStatus

  """Filter by the start date of the media"""
  startDate: Date
  """Filter by the end date of the media"""
  endDate: Date

  """Cursor from where to start"""
  at: Id
  """How many pages before the cursor to return"""
  before: Int
  """How many pages after the cursor to return"""
  after: Int
}

type MediaPage {
  """The current page"""
  firstPageCursor: Id
  """The current page"""
  previousPageCursor: Id
  """The current page"""
  currentPageCursor: Id
  """The first page"""
  nextPageCursor: Id
  """The last page cursor"""
  lastPageCursor: Id
  """Total number of items on the current page"""
  currentPageNodeCount: Int
  """The total number of items. Note: This value is not guaranteed to be accurate, do not rely on this for logic"""
  totalNodeCount: Int
  """Total number of items before the current page. Note: This value is not guaranteed to be accurate, do not rely on this for logic"""
  beforeCurrentPageNodeCount: Int
  """Total number of items after the current page. Note: This value is not guaranteed to be accurate, do not rely on this for logic"""
  afterCurrentPageNodeCount: Int
  """The media page nodes"""
  nodes: [Media!]!
}

extend type Subscription {
  media(input: MediaInput!): Media
  mediaPage(input: MediaPageInput!): MediaPage!
}
