
enum MediaType {
  TV
  MOVIE
  ANIME
  """Special episodes that have been included in DVD/Blu-ray releases, picture dramas, pilots, etc"""
  SPECIAL
  """(Original Video Animation) Anime that have been released directly on
DVD/Blu-ray without originally going through a theatrical release or
television broadcast"""
  OVA
  """(Original Net Animation) Anime that have been originally released online or are only available through streaming services."""
  ONA
  """Live action media such as movies or TV show"""
  LIVE_ACTION
}

enum MediaStatus {
  """Has completed and is no longer being released"""
  FINISHED
  """Currently releasing"""
  RELEASING
  """To be released at a later date"""
  NOT_YET_RELEASED
  """Ended before the work could be finished"""
  CANCELLED
  """Is currently paused from releasing and will resume at a later date"""
  HIATUS
}

type Media {
  """Uri consists of the `origin` and `id` fields in the format `origin:id`"""
  uri: String!
  """String that is used to target a specific origin, e.g `google` or `yt` for youtube"""
  origin: String!
  """An id that references a specific resource within the origin space"""
  id: String!
  """An url to the media resource"""
  url: String
  aggregated: Boolean
  """Links to external/other resources related to itself"""
  handles: [Media!]
  handleOf: [Media!]
  titles: [MediaTitle!]
  type: MediaType
  status: MediaStatus
  shortDescriptions: [MediaShortDescription!]
  descriptions: [MediaDescription!]
  trailers: [MediaTrailer!]
  covers: [MediaCover!]
  banners: [MediaBanner!]
  externalLinks: String
  averageScore: Int
  popularity: Int
  startDate: Date
  endDate: Date
  isAdult: Boolean
  episodeCount: Int
  episodes: [Episode!]
}

type MediaTitle {
  language: String!
  title: String!
  score: Float
}

type MediaShortDescription {
  language: String!
  shortDescription: String!
}

type MediaDescription {
  language: String!
  description: String!
}

type MediaTrailer {
  """Uri consists of the `origin` and `id` fields in the format `origin:id`"""
  uri: String!
  """String that is used to target a specific origin, e.g `google` or `yt` for youtube"""
  origin: String!
  """An id that references a specific resource within the origin space"""
  id: String!
  """An url to the media resource"""
  url: String
  language: String
  thumbnail: String
}

type MediaCover {
  language: String
  url: String!
  height: Int
  width: Int
  """Average #hex color of cover image"""
  color: String
}

type MediaBanner {
  language: String
  url: String!
  height: Int
  width: Int
  """Average #hex color of cover image"""
  color: String
}


input MediaInput {
  uri: ID
  origin: ID
  language: String
  id: ID
  url: String
}

enum MediaSort {
  POPULARITY
  POPULARITY_DESC
}

input MediaPageInput {
"""Filter by media IDs"""
  nodes: [MediaInput!]
  """Filter by search terms"""
  search: String
  """Filter by the media's current release status"""
  status: MediaStatus

  sorts: [MediaSort!]

  """Filter by the start date of the media"""
  startDate: Date
  """Filter by the end date of the media"""
  endDate: Date

  """Cursor from where to start"""
  at: Id
  """How many pages before the cursor to return"""
  before: Int
  """How many pages after the cursor to return"""
  after: Int
}

type MediaPage {
  """The current page"""
  firstPageCursor: Id
  """The current page"""
  previousPageCursor: Id
  """The current page"""
  currentPageCursor: Id
  """The first page"""
  nextPageCursor: Id
  """The last page cursor"""
  lastPageCursor: Id
  """Total number of items on the current page"""
  currentPageNodeCount: Int
  """The total number of items. Note: This value is not guaranteed to be accurate, do not rely on this for logic"""
  totalNodeCount: Int
  """Total number of items before the current page. Note: This value is not guaranteed to be accurate, do not rely on this for logic"""
  beforeCurrentPageNodeCount: Int
  """Total number of items after the current page. Note: This value is not guaranteed to be accurate, do not rely on this for logic"""
  afterCurrentPageNodeCount: Int
  """The media page nodes"""
  nodes: [Media!]!
}

extend type Subscription {
  media(input: MediaInput!): Media
  mediaPage(input: MediaPageInput!): MediaPage!
}
