scalar JSON
scalar Id
scalar Date

enum MediaType {
  TV
  MOVIE
  ANIME
  """Special episodes that have been included in DVD/Blu-ray releases, picture dramas, pilots, etc"""
  SPECIAL
  """(Original Video Animation) Anime that have been released directly on
DVD/Blu-ray without originally going through a theatrical release or
television broadcast"""
  OVA
  """(Original Net Animation) Anime that have been originally released online or are only available through streaming services."""
  ONA
  """Live action media such as movies or TV show"""
  LIVE_ACTION
}

enum MediaStatus {
  """Has completed and is no longer being released"""
  FINISHED
  """Currently releasing"""
  RELEASING
  """To be released at a later date"""
  NOT_YET_RELEASED
  """Ended before the work could be finished"""
  CANCELLED
  """Is currently paused from releasing and will resume at a later date"""
  HIATUS
}

enum PlaybackSourceType {
  IFRAME
  CUSTOM
  OTHER
}

type Media {
  """Uri consists of the `origin` and `id` fields in the format `origin:id`"""
  uri: String!
  """String that is used to target a specific origin, e.g `google` or `yt` for youtube"""
  origin: String!
  """An id that references a specific resource within the origin space"""
  id: String!
  """An url to the media resource"""
  url: String
  aggregated: Boolean
  """Links to external/other resources related to itself"""
  handles: [Media!]
  handleOf: [Media!]
  titles: [MediaTitle!]
  type: MediaType
  status: MediaStatus
  shortDescriptions: [MediaShortDescription!]
  descriptions: [MediaDescription!]
  trailers: [MediaTrailer!]
  covers: [MediaCover!]
  banners: [MediaBanner!]
  externalLinks: String
  averageScore: Int
  popularity: Int
  startDate: Date
  endDate: Date
  isAdult: Boolean
  episodeCount: Int
  episodes: [Episode!]
}

type MediaTitle {
  language: String!
  title: String!
  Media: Media
  mediaUri: String
}

type MediaShortDescription {
  language: String!
  shortDescription: String!
  Media: Media
  mediaUri: String
}

type MediaDescription {
  language: String!
  description: String!
  Media: Media
  mediaUri: String
}

type MediaTrailer {
  """Uri consists of the `origin` and `id` fields in the format `origin:id`"""
  uri: String!
  """String that is used to target a specific origin, e.g `google` or `yt` for youtube"""
  origin: String!
  """An id that references a specific resource within the origin space"""
  id: String!
  """An url to the media resource"""
  url: String
  language: String!
  thumbnail: String
  Media: Media
}

type MediaCover {
  language: String!
  url: String!
  height: Int
  width: Int
  """Average #hex color of cover image"""
  color: String
  Media: Media
}

type MediaBanner {
  language: String!
  url: String!
  height: Int
  width: Int
  """Average #hex color of cover image"""
  color: String
  Media: Media
}

type Episode {
  """Uri consists of the `origin` and `id` fields in the format `origin:id`"""
  uri: String!
  """String that is used to target a specific origin, e.g `google` or `yt` for youtube"""
  origin: String!
  """An id that references a specific resource within the origin space"""
  id: String!
  """An url to the media resource"""
  url: String
  aggregated: Boolean!
  titles: [EpisodeTitle!]
  shortDescriptions: [EpisodeShortDescription!]
  descriptions: [EpisodeDescription!]
  releaseDate: Date
  relativeNumber: Int
  absoluteNumber: Int
  thumbnails: [EpisodeThumbnail!]
  playbackSources: [PlaybackSource!]
  Media: Media
}

type EpisodeTitle {
  language: String!
  title: String!
  Episode: Episode
  episodeUri: String
}

type EpisodeShortDescription {
  language: String!
  shortDescription: String!
  Episode: Episode
  episodeUri: String
}

type EpisodeDescription {
  language: String!
  description: String!
  Episode: Episode
  episodeUri: String
}

type EpisodeThumbnail {
  language: String!
  url: String!
  height: Int
  width: Int
  """Average #hex color of cover image"""
  color: String
  Episode: Episode
}

type PlaybackSource {
  """Uri consists of the `origin` and `id` fields in the format `origin:id`"""
  uri: String!
  """String that is used to target a specific origin, e.g `google` or `yt` for youtube"""
  origin: String!
  """An id that references a specific resource within the origin space"""
  id: String!
  """An url to the media resource"""
  url: String
  type: PlaybackSourceType!
  """JSON data for custom players"""
  data: JSON
  Episode: Episode
}

type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

type Subscription {
  _empty: String
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
