scalar JSON
scalar Id
scalar Date

type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

type Subscription {
  _empty: String
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
