
type Episode {
  """Stable unique identifier that persists across URI changes and source additions"""
  _id: String!
  """Uri consists of the `origin` and `id` fields in the format `origin:id`"""
  uri: String!
  """String that is used to target a specific origin, e.g `google` or `yt` for youtube"""
  origin: String!
  """An id that references a specific resource within the origin space"""
  id: String!
  """An url to the media resource"""
  url: String
  """Uri to the media resource"""
  mediaUri: String!
  """Links to external/other resources related to itself"""
  handles: [Episode!]
  handleOf: [Episode!]
  score: Float
  titles: [EpisodeTitle!]
  shortDescriptions: [EpisodeShortDescription!]
  descriptions: [EpisodeDescription!]
  releaseDate: Date
  relativeNumber: Int
  absoluteNumber: Int
  thumbnails: [EpisodeThumbnail!]
  playbackSources: [PlaybackSource!]
  seasonNumber: Int
  episodeNumber: Int
  absoluteEpisodeNumber: Int
}

type EpisodeTitle {
  language: String!
  title: String!
  score: Float
}

type EpisodeShortDescription {
  language: String!
  shortDescription: String!
}

type EpisodeDescription {
  language: String!
  description: String!
}

type EpisodeThumbnail {
  language: String
  url: String!
  height: Int
  width: Int
  """Average #hex color of cover image"""
  color: String
}
